# NOTE: This `0_webui.yml` file is saved in the buildkite WebUI.
# Editing it here has no effect, we simply include this
# to keep track of what is implemented in the WebUI!

steps:
  # In the WebUI, the `cryptic` launch job _must_ be the first job to run
  - label: ":rocket: Launch pipelines"
    plugins:
      - staticfloat/cryptic#v2:
          signed_pipelines:
            - pipeline: .buildkite/gateware.yml
              signature_file: .buildkite/gateware.yml.signature
          unsigned_pipelines:
            - .buildkite/pipeline.yml
    command: "true"
    agents:
      cryptic_capable: "true"
      # Eventually, fix the windows problems in cryptic
      os: "linux"
