steps:
  - label: ":linux: :corn: :hammer_and_wrench: Build NVIDIA and litepcie kernel modules"
    plugins:
      # buildkite does not yet have a way to specify `--depth=1` for `git submodule update`
      - thedyrt/skip-checkout#v0.1.1: ~
      - JuliaCI/julia#v1:
          version: '1'
      - staticfloat/sandbox#v1:
          rootfs_url: "https://github.com/JuliaComputing/rootfs-images/releases/download/kernel-builder-2022-07-12/kernel_builder.x86_64.tar.gz"
          rootfs_treehash: "c0660b88baa6e9607ef859b5daa349fc8de8712c"
          workspaces:
            - "/cache/repos:/cache/repos"
    commands: |
      echo "--- Clone repo (note, this doesn't work for 3rd party forks)"
      git clone $${BUILDKITE_GIT_CLONE_FLAGS} "$${BUILDKITE_REPO}" .
      git checkout --force "$${BUILDKITE_COMMIT}"
      git submodule update --init --recursive --force --depth=1

      # We must do a full kernel build to get `Module.symvers`, which makes the nvidia build happy
      echo "--- Build kernel"
      KERNEL_DIR=$$(pwd)/software/kernel
      make -C "$${KERNEL_DIR}" defconfig -j$$(nproc)
      make -C "$${KERNEL_DIR}" -j$$(nproc)

      echo "--- Bundle kernel"
      cp -Lva software/kernel/arch/$$(uname -m)/boot/bzImage bzImage

      echo "--- Build NVIDIA driver"
      NVIDIA_MODLIB=$$(pwd)/nvidia-build
      mkdir -p "$${NVIDIA_MODLIB}"
      make -C software/nvidia-driver -j$$(nproc) SYSSRC="$${KERNEL_DIR}" MODLIB="$${NVIDIA_MODLIB}"
      make -C software/nvidia-driver -j$$(nproc) SYSSRC="$${KERNEL_DIR}" MODLIB="$${NVIDIA_MODLIB}" modules_install

      echo "--- Bundle NVIDIA kernel modules"
      tar -cvzf nvidia-kernel-modules.tar.gz -C "$${NVIDIA_MODLIB}" .

      echo "--- Build litepcie kernel modules"
      make -C software/litepcie-kernel-module -j$$(nproc)
      
      echo "--- Bundle litepci kernel modules"
      LITEPCIE_KOS=$$(cd software/litepcie-kernel-module; ls *.ko)
      tar -cvzf litepcie-kernel-modules.tar.gz -C software/litepcie-kernel-module $${LITEPCIE_KOS}
    artifact_paths:
      - "nvidia-kernel-modules.tar.gz"
      - "litepcie-kernel-modules.tar.gz"
      - "bzImage"
    agents:
      sandbox_capable: "true"
      os: "linux"
      arch: "x86_64"


  - label: ":linux: :hammer_and_wrench: Build litepcie user library"
    plugins:
      - JuliaCI/julia#v1:
          version: '1'
      - staticfloat/sandbox#v1:
          rootfs_url: "https://github.com/JuliaComputing/rootfs-images/releases/download/kernel-builder-2022-07-12/kernel_builder.x86_64.tar.gz"
          rootfs_treehash: "c0660b88baa6e9607ef859b5daa349fc8de8712c"
          workspaces:
            - "/cache/repos:/cache/repos"
    commands: |
      echo "--- Download CUDA"
      make -C software/litepcie-user-library download-cuda

      echo "--- Build litepcie user library"
      LLP_BUILD=$$(pwd)/build
      mkdir -p $${LLP_BUILD}
      make -C software/litepcie-user-library -j$$(nproc) prefix=$${LLP_BUILD} install

      echo "--- Bundle liblitepcie"
      tar -czvf liblitepcie.tar.gz -C $${LLP_BUILD}
    artifact_paths:
      - "liblitepcie.tar.gz"
    agents:
      sandbox_capable: "true"
      os: "linux"
      arch: "x86_64"
